name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            git \
            curl \
            gtk4 \
            libadwaita \
            wf-recorder

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      
      - name: Build
        run: |
          source $HOME/.cargo/env
          cargo build --verbose
      
      - name: Run tests
        run: |
          source $HOME/.cargo/env
          cargo test --verbose

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            git \
            curl \
            gtk4 \
            libadwaita \
            wf-recorder

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      
      - name: Install Rust components
        run: |
          source $HOME/.cargo/env
          rustup component add rustfmt clippy
      
      - name: Check formatting
        run: |
          source $HOME/.cargo/env
          cargo fmt --all -- --check
      
      - name: Clippy
        run: |
          source $HOME/.cargo/env
          cargo clippy -- -D warnings

  security_audit:
    name: Security audit
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            git \
            curl \
            gtk4 \
            libadwaita \
            wf-recorder

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      
      - name: Install cargo-audit
        run: |
          source $HOME/.cargo/env
          cargo install cargo-audit
      
      - name: Run security audit
        run: |
          source $HOME/.cargo/env
          cargo audit
